//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Commentaire = new HashSet<Commentaire>();
        }
    
        public int idArticle { get; set; }
        [Display(Name = "Catégorie")]
        public int idCategorie { get; set; }
        [Display(Name = "Titre")]
        public string titre { get; set; }
        [Display(Name = "Contenu")]
        public string contenu { get; set; }
        [Display(Name = "Addedum")]
        public string addedum { get; set; }
        [Display(Name = "Date de publication")]
        public System.DateTime date_publication { get; set; }
        [Display(Name = "Date addedum")]
        public Nullable<System.DateTime> date_addedum { get; set; }
        [UIHint("BoolPublished")]
        [Display(Name = "Publié")]
        public bool publie { get; set; }
        [Display(Name = "Image")]
        public string image { get; set; }
        [Required(ErrorMessage = "La description doit être renseignée"), 
            Display(Name = "Description")]
        public string description { get; set; }

        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentaire> Commentaire { get; set; }
    }
}
