//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Commentaire> Commentaire { get; set; }
        public virtual DbSet<Lecteur> Lecteur { get; set; }
        public virtual DbSet<Paramétrage> Paramétrage { get; set; }
    
        public virtual ObjectResult<LoginAdminByUsernamePassword_Result> LoginAdminByUsernamePassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginAdminByUsernamePassword_Result>("LoginAdminByUsernamePassword", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<CategoriesListe_Result> CategoriesListe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CategoriesListe_Result>("CategoriesListe");
        }
    
        public virtual ObjectResult<ArticlesListe_Result> ArticlesListe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ArticlesListe_Result>("ArticlesListe");
        }
    
        public virtual ObjectResult<LoginLecteurByUsernamePassword_Result> LoginLecteurByUsernamePassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginLecteurByUsernamePassword_Result>("LoginLecteurByUsernamePassword", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<DerniersArticlesListe_Result> DerniersArticlesListe(Nullable<int> idCategorie, string search)
        {
            var idCategorieParameter = idCategorie.HasValue ?
                new ObjectParameter("idCategorie", idCategorie) :
                new ObjectParameter("idCategorie", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DerniersArticlesListe_Result>("DerniersArticlesListe", idCategorieParameter, searchParameter);
        }
    }
}
