//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int idCommentaire { get; set; }
        public int idArticle { get; set; }
        public int idLecteur { get; set; }
        public string contenu { get; set; }
        public System.DateTime date { get; set; }
        public string reponse { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Lecteur Lecteur { get; set; }
    }
}
